### ISSUE TITLE
Global - Implement New Typography

### ISSUE THREAD

**Issue by melissacohen** [shifteight-dev/HarleyandCo#1]

**Comment by CSamuelLents** [comment]
@melissacohen 

Reiterating from the email as promised - We will either need details mapping the old fonts/font-sizes to the updated versions, or screenshots of each page annotating the changes for this. Thanks.

**Comment by melissacohen** [comment]
Hi @CSamuelLents Kyla will provide this - is there a way to get her into github? I tried to assign her here but she wasn't coming up.

Thanks!

**Comment by CSamuelLents** [comment]
@melissacohen I just added Kyla as a collaborator on this project, so as soon as she accepts the invite you should be able to assign her.
