### ISSUE TITLE
Uploads Folder

### ISSUE THREAD

**Issue by CSamuelLents** [shifteight-dev/HarleyandCo#15]
@melissacohen 

I need a copy of the "/uploads" folder from the live site, if possible. It would be inside of the "wp-content" folder. It has all of the images that have been uploaded through the admin. As it is now, most of the images on our local version of the site are broken.

If you can give me ssh access to your live server, we would be happy to take care of that ourselves, but either way works.

Thanks

**Comment by melissacohen** [comment]
Hi @CSamuelLents this will have to been downloaded directly from the production server. Kyla now has access to this and can provide what you need.
