### ISSUE TITLE
Homepage QA

### ISSUE THREAD

**Issue by kylamedina** [shifteight-dev/HarleyandCo#16]
- [x] Remove bottom padding from `.project-item-title`
- [x] `h1.SE_header line-height 1.2`
- [x] `#SE_projects .SE_taglist-container .SE_taglist li` (this is not such a good selector, its too deep) `margin: 0 1.5%; letter-spacing: 2px`
- [x] Hamburger button width should be 3.6rem and the margin-top of ':before,:after' should be 1.1rem and 2.2rem
- [x] Sorry, can we make `#SE_projects .project-item .project-item-title` margin-top: 18px
- [x] Can you add an underline on the active filter? The Sketch file has been updated.
- [x] Sorry, can you change `#SE_projects .SE_taglist-container .SE_taglist` li to `margin: 0 20px;` I'm going to make a mobile version of this as well.
- [x] on mobile the project title and subtitle get spaced out differently than on larger screens.
- [x] change to non-italic in the project name and remove the font from CSS or the head, however you're doing it.
- [x] can we maintain the aspect ration of the project thumbnails http://codepen.io/kylamedina/pen/pNWNMm
- [x] use the SVG logo
- [x] On MOBILE ONLY, drop the Filtering system.

**Comment by histevele** [comment]
- [ ] #SE_projects #brands-list - For the logo footer, have bottom padding of 4 rem (same as padding-top).

**Comment by kylamedina** [comment]
- [ ] Sorry, can you change `#SE_projects .SE_taglist-container .SE_taglist` li to `margin: 0 20px;` I'm going to make a mobile version of this as well.
