### ISSUE TITLE
Backend Error (Add New)

### ISSUE THREAD

**Issue by histevele** [shifteight-dev/HarleyandCo#21]
When adding a new module, work or whatever... I get the attached error. 
![screen shot 2016-12-01 at 1 40 48 pm](https://cloud.githubusercontent.com/assets/24254189/20807161/c81d61f2-b7cb-11e6-965d-721261ddd2cc.png)

**Comment by CSamuelLents** [comment]
@histevele 

There were some conflicts due to being on an older version of Wordpress, so we went ahead and made the upgrade to the newest version. This should be resolved now.

**Comment by histevele** [comment]
Confirmed working on my end. Thanks for the quick turnaround!
