### ISSUE TITLE
Menu 

### ISSUE THREAD

**Issue by histevele** [shifteight-dev/HarleyandCo#24]
- [x] center align social icons with equal margins on left and right
- [x] when clicking menu, page shifts to the right because the scroll bar hides. how to fix?
- [x] the close icon needs to be in the exact same position as the hamburger button. In fact, it should be the same elements. We want to do an animation like this: https://dribbble.com/shots/1509364-HTML-Hamburger-Close-Animation

**Comment by CSamuelLents** [comment]
@histevele 

I am having trouble replicating the first 2 of these issues. What browser/OS are you seeing these issues on?

**Comment by histevele** [comment]
@CSamuelLents 

I am using Chrome on OSX Yosemite. 

I have attached an image that helps with the first issue. It is very slight.
![screen shot 2016-12-07 at 2 58 57 pm](https://cloud.githubusercontent.com/assets/24254189/20984441/440adea4-bc8e-11e6-8633-10b22bbaa71b.jpg)

**Comment by kylamedina** [comment]
@CSamuelLents for the first one, you only have margins on the right side of the `a` tag. Make it equal margins. Ignore the second on for right now, we are testing other computers and browsers.

**Comment by histevele** [comment]
@CSamuelLents As for the second issue, we tried on a laptop and it was fine. I think it might be an issue with people who are using wacom tablets, since all tablet users here have the same problem. Let's close it for now.
